### ISSUE TITLE
The sentiments are varying every time when i run it for the same sentence.

### ISSUE THREAD

**Issue by man0007** [yya518/FinBERT#15]
I have created my own sentence "there is a abundance of capital because of good profits" to test the sentiment prediction for the fine-tuned model using the notebook given: "FinBert Model Example.ipynb". 

When I ran for the first time I got the result as 'positive': https://prnt.sc/vf3fnb 
When I ran for the second time I got the result as 'neutral': https://prnt.sc/vf3fcr

Why is this variation happening? How can we trust the results from this model if it is not stable?

**Comment by yya518** [comment]
Thanks for reporting this. There should be model.eval() in the notebook. It's fixed now.

**Comment by m1996** [comment]
Hi
I am facing the same problem. I just commented model.load_state_dict(torch.load(fine_tuned_weight_path)) ...
