### ISSUE TITLE
Migration to transformers

### ISSUE THREAD

**Issue by Dhruv26** [yya518/FinBERT#16]
Are there any plans on migrating the current model to the newer **transformers** library by hugging face? I want to use it with the **sentence-transformer** library but it seems like it can only run with the newer transformer model.

**Comment by yya518** [comment]
Great suggestion. Will keep you posted.

**Comment by Dhruv26** [comment]
@yya518 will be happy to help!

**Comment by yya518** [comment]
glad to inform y'all that the it's integrated with transformers.
