### ISSUE TITLE
FinBERT pipeline vs Finbert Model Example code result difference

### ISSUE THREAD

**Issue by eadsa1998** [yya518/FinBERT#22]
My collaborators and I were experimenting with FinBERT by comparing the results of your code from the Finbert Model Example notebook to the results of using the transformer code in a HuggingFace pipeline. of the 7 we tested it on, all came out with different scores, but 3 came out with different labels altogether. We were wondering if you knew what the reason for that might be? I can upload the code that we used if that would be helpful.

**Comment by market-structure** [comment]
Could you be more specific? Are you saying that our notebook, or transformer's pipeline, produces different scores? and 7 of what? sentences?

**Comment by yya518** [comment]
Could you be more specific? Are you saying that our notebook, or transformer's pipeline, produces different scores? and 7 of what? sentences?
