### ISSUE TITLE
Is there sentiment score or probability of positive/neutral/negative?

### ISSUE THREAD

**Issue by petric3** [yya518/FinBERT#27]
Thank you for the great library.

I went through example and there are only labels, i.e. positive, neutral and negative for the text's sentiment. I'm wondering if there's any score or probability deciding what text is positive, neutral or negative? 

I was looking in attributes, i.e. `dir(outputs)` or `dir(tourch)` but did not find any such value, which would be indeed useful to know.

**Comment by yya518** [comment]
Yes, FinBERT produces probabilities for each label.
