### ISSUE TITLE
script to finetune finbert for downstream task

### ISSUE THREAD

**Issue by luke4u** [yya518/FinBERT#28]
Hi @yya518 ,

Thank you so much for sharing this wonderful work. 

I have read the repo and [medium ](https://medium.com/prosus-ai-tech-blog/finbert-financial-sentiment-analysis-with-bert-b277a3607101)article, but seems not find a script on how to fine tune Finbert model for downstream task. Would be possible to share a script to do such? 

Thanks again!

**Comment by yya518** [comment]
it's here
https://github.com/yya518/FinBERT/blob/master/finetune.ipynb
