### ISSUE TITLE
What is the max_seq_len on which this model (FinBert_FinVocab_Uncased) has been trained?

### ISSUE THREAD

**Issue by man0007** [yya518/FinBERT#7]

**Comment by yya518** [comment]
Following the original BERT training, we set a maximum sentence length of 128 tokens, and train the model until the training loss starts to converge. We then continue training the model allowing sentence lengths up to 512 tokens.

**Comment by man0007** [comment]
Which one would give better accuracy? max-seq 256 or 512?
